name: talking-head-anime
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - cudatoolkit=10.1.243
  - dlib=19.19
  - freetype=2.9.1
  - intel-openmp=2019.4
  - jpeg=9c
  - libpng=1.6.37
  - libtiff=4.1.0
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1d
  - pillow=7.0.0
  - pip=19.3.1
  - python=3.8.1
  - pytorch=1.4.0
  - setuptools=44.0.0
  - six=1.13.0
  - sqlite=3.30.1
  - tk=8.6.8
  - torchvision=0.5.0
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - opencv-python==4.1.2.30

